#This is a Build Deploy Pipeline for .NET 6 Web App to Azure App Service using Azure DevOps Pipeline

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  targetRuntime: 'linux-x64'
  azureSPNName: 'MinimalApiSC'
  azureAppServiceName: 'mjeon-minimalapi'

# Build the app for .NET 6 framework
steps:
# TEST PowerShell
#- task: PowerShell@2
#  displayName: 'PowerShell test'
#  inputs:
#    targetType: 'inline'
#    script: |
#      Write-Host "Current user: $([System.Security.Principal.WindowsIdentity]::GetCurrent().Name)"
#      Get-AzSubscription

# TEST AzurePowerShell
- task: AzurePowerShell@5
  displayName: 'AzurePowerShell test'
  inputs:
    azureSubscription: 'mjeon (3577af52-1cb5-4fe3-882a-18705fccce4e)'
    ScriptType: InLineScript
    InLine: |
      Get-AzSubscription

- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET 6 Application'

# Publish it as .NET 6 self contained application for linux runtime
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --runtime $(targetRuntime) --self-contained --output $(Build.ArtifactStagingDirectory) --property:maxcpucount=1'
    zipAfterPublish: True

# Package the file and uploads them as an artifact of the build
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'MinimalAPI'

#Publish it to the Azure App Service
- task: AzureWebApp@1
  inputs:
    appType: webAppLinux
    azureSubscription: $(azureSPNName) #this is the name of the SPN
    appName: $(azureAppServiceName) #App Service's unique name
    package: $(Build.ArtifactStagingDirectory)/**/*.zip

  
